version: '3.8'

services:
  nestjs:
    build: .
    container_name: nestjs
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env.docker
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env.docker
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER']
      interval: 10s
      timeout: 5s
      retries: 12

volumes:
  postgres_data:
